
###　スターを追加して平均を出すメソッド
PUT http://localhost:8080/api/items/addstar/1?star=3

###　Create
POST http://localhost:8080/api/items
Content-Type: application/json

  {
    "name": "りんご",
    "price": 8888,
    "memo": "gmail 甘い　青森SS",
    "starCount":0,
    "star":0
  }

### READ (findAll)
GET http://localhost:8080/api/items

###　UPDATE
PUT http://localhost:8080/api/items/1
Content-Type: application/json

  {
    "name": "りんご",
    "price": 8888,
    "memo": "gmail 甘い　青森SS"
  }

### DELETE
Delete http://localhost:8080/api/items/1

### カラム内のキーワード検索（空白でsplit）
GET http://localhost:8080/api/items/findAllByColumn?column=name&keyword= りんご  みかん. ぶどう

